CREATE table place(id int identity primary key, name varchar(100));
INSERT into place values(0, 'NTNU');
INSERT into place values(1, 'UIB');
INSERT into place values(2, 'UIO');
CREATE table event(id int identity primary key, title varchar(100), event_date date, place_id int, is_open boolean, is_random boolean);
INSERT into event values(0, 'Bedpres abakus', '2011-10-10', 0, 'true', true);
INSERT into event values(1, 'itDAGENE', '2011-09-05', 0, 'false', false);
INSERT into event values(2, 'Kjedelig sak', '2011-10-03', 1, 'false', false);
CREATE table question(id int identity primary key, question varchar(255), answer varchar(100));
INSERT into question values(0, 'intvalue(leet) blir ...', '1337');
INSERT into question values(1, 'måned til nasjonaldag', 'mai');
INSERT into question values(2, 'high performance (...)', 'delivered');
INSERT into question values(3, 'tiger woods spiller hvilken sport?', 'golf');
CREATE table event_question(question_id int, event_id int, description varchar(255), activation_code varchar(100), post_num int, PRIMARY KEY(question_id, event_id));
INSERT into event_question values(0, 0, 'EL5', 'abc', 0);
INSERT into event_question values(2, 0, 'EL6', 'abc', 2);
INSERT into event_question values(3, 0, 'S2', 'abc', 1);
INSERT into event_question values(3, 1, 'S2', 'abc', 3);
CREATE table event_user(event_id int, email varchar(100), nick varchar(100), phone varchar(12), answered int, finish_time timestamp, PRIMARY KEY(event_id, email));
INSERT into event_user values(0, 'abc@de.fg', 'nickman', '48199669', 1, '2011-10-10 11:37:00');
INSERT into event_user values(1, 'abc@de.fg', 'nickman', '48199669', 1, '2011-10-10 09:47:03');
INSERT into event_user values(1, 'waeff@wegf.com', 'per', '113', 1, '2011-10-10 13:32:04');
INSERT into event_user values(1, 'weaf@ewf.com', 'axel', '112', 0, '2011-10-10 10:23:04');